INSERT INTO skill_scale VALUES(11, 41, 6, 5, 1, 1, 10, 1);
INSERT INTO stat_level_scale VALUES
  ('str', 10, 5, 10, 5),
  ('vit', 10, 5, 10, 5),
  ('spd', 10, 5, 10, 5),
  ('dex', 10, 5, 10, 5),
  ('int', 10, 5, 10, 5),
  ('wis', 10, 5, 10, 5);

INSERT INTO stat_skill_scale VALUES
  ('fire', 'str', 10),
  ('water', 'str', 6),
  ('lightning', 'str', 4),
  ('wind', 'str', 0),
  ('earth', 'str', 6),
  ('sonic', 'str', 4),
  ('personal', 'str', 10),
  ('material', 'str', 8),
  ('shift', 'str', 6),
  ('life', 'str', 2),
  ('space', 'str', 0),
  ('gravity', 'str', 4),
  ('fire', 'vit', 0),
  ('water', 'vit', 8),
  ('lightning', 'vit', 2),
  ('wind', 'vit', 8),
  ('earth', 'vit', 10),
  ('sonic', 'vit', 0),
  ('personal', 'vit', 6),
  ('material', 'vit', 10),
  ('shift', 'vit', 8),
  ('life', 'vit', 6),
  ('space', 'vit', 2),
  ('gravity', 'vit', 0),
  ('fire', 'spd', 8),
  ('water', 'spd', 4),
  ('lightning', 'spd', 8),
  ('wind', 'spd', 6),
  ('earth', 'spd', 0),
  ('sonic', 'spd', 10),
  ('personal', 'spd', 8),
  ('material', 'spd', 0),
  ('shift', 'spd', 2),
  ('life', 'spd', 0),
  ('space', 'spd', 4),
  ('gravity', 'spd', 10),
  ('fire', 'dex', 4),
  ('water', 'dex', 0),
  ('lightning', 'dex', 6),
  ('wind', 'dex', 10),
  ('earth', 'dex', 2),
  ('sonic', 'dex', 8),
  ('personal', 'dex', 2),
  ('material', 'dex', 4),
  ('shift', 'dex', 10),
  ('life', 'dex', 4),
  ('space', 'dex', 8),
  ('gravity', 'dex', 2),
  ('fire', 'int', 6),
  ('water', 'int', 2),
  ('lightning', 'int', 10),
  ('wind', 'int', 2),
  ('earth', 'int', 4),
  ('sonic', 'int', 6),
  ('personal', 'int', 0),
  ('material', 'int', 2),
  ('shift', 'int', 4),
  ('life', 'int', 8),
  ('space', 'int', 10),
  ('gravity', 'int', 6),
  ('fire', 'wis', 2),
  ('water', 'wis', 10),
  ('lightning', 'wis', 0),
  ('wind', 'wis', 4),
  ('earth', 'wis', 8),
  ('sonic', 'wis', 2),
  ('personal', 'wis', 4),
  ('material', 'wis', 6),
  ('shift', 'wis', 0),
  ('life', 'wis', 10),
  ('space', 'wis', 6),
  ('gravity', 'wis', 8);

INSERT INTO vital_scale VALUES
  (600, 30, 20, 2, 1);
