spring:
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5432/cyberscape
    username: cyberscape
    password: ENC(27u95JIGEtfR7TfXGnNV5yBz7AbWycu3FkvqevuQOb8=)
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ENC(q8cA64F/gK7AhTPMTaC5U80l/7Xf59OZZTgXHToQxzQ=)
            client-secret: ENC(WtWTNaMtAHwVvgUS/zmmasa6iT+iWylWvJ5WcDoIOvx34CsQL67/KF/l5n/aJdaM)
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - identify
            redirectUriTemplate: "{baseUrl}/login/oauth2/code/discord"
            clientName: Cyberscape Neo Discord Bot
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: username
server:
  address: 127.0.0.1
  port: 8080
  useForwardHeaders: true
  servlet:
    context-path: /game
discord:
  token: ENC(4Mxyeed8sDnvO0FVeTLboz3mrFsP3Bw0qBHdXvTXa3z3cSlO8/9rUx5Sj29m9mnqb2uL6OXlzvrFMmI1LkFP6cwBiM/q02Cd)
game:
  baseUrl: https://xathien.me/game/
---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://192.168.1.2:5432/cyberscape
server:
  address: 0.0.0.0
---
spring:
  profiles: production
game:
  baseUrl: https://titaniumtemplar.com/game/